services:
  - type: web
    name: practice_web
    env: docker
    plan: free
    region: oregon
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/practice_web-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_VERSION
        value: 17
